# Generated by Django 3.2.7 on 2021-09-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0002_auto_20210925_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Date',
            new_name='date',
        ),
    ]
