# Generated by Django 3.2.7 on 2021-09-25 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hall', '0003_rename_date_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepteur',
            name='name',
        ),
        migrations.AddField(
            model_name='recepteur',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
