# Generated by Django 3.2.7 on 2021-09-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0004_auto_20210925_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_de_profil',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
