# Generated by Django 3.2.7 on 2021-10-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0008_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
