# Generated by Django 3.2.7 on 2021-10-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0009_auto_20211002_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/file'),
        ),
    ]
