# Generated by Django 3.2.7 on 2021-10-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0010_alter_messages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='recepteur',
            field=models.ManyToManyField(blank=True, null=True, to='Hall.Recepteur'),
        ),
    ]
