# Generated by Django 3.2.7 on 2021-10-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0012_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={},
        ),
    ]
