# Generated by Django 3.2.7 on 2021-10-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0013_alter_videos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='static/file'),
        ),
    ]
