# Generated by Django 3.2.7 on 2021-10-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0015_auto_20211005_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/file'),
        ),
    ]
