# Generated by Django 3.2.7 on 2021-11-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0019_auto_20211112_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
