# Generated by Django 3.2.7 on 2021-11-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0020_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
